print("hello world")
a=5
b=6
sum=a+b
print(sum)
type(a)
x='hello'
type(x)
a=3j+2
type(a)
f=3.6
type(f)
s=True
type(s)
f-b
f*b
f/b
f%b
f**b
f//b
b=5
a=26
a//b
a%b
x=5
x+=3
x-=3
x*=3
x/=3
x%=3
x//=3
x**=3
x&=3
mylist=['apple','banana','cherry']
type(mylist)
len(mylist)
mylist[1]
mylist[2]
mylist[-2]
mylist[-1]
mylist=['apple','banana','cherry','grape','mango','pomogranate']
mylist[1:3] #slicing
mylist[-4:-2]
mylist[-3:-1]
mylist[2:4]
mylist[::2]
mylist[::3]
mylist[::-1]
mylist[:3]
mylist[3:]
mylist.append('kiwi')
mylist
mylist.insert(2,'pineapple')
mylist
mylist[2]='watermelon'
mylist
mylist[3]='blackcurrant'
mylist2=['carrot','cabbage','cucumber','brinjal']
mylist2
mylist2[1:3]=['onion','tomato']
mylist2
#comment-remove methods
mylist
mylist.remove('banana')
mylist
mylist.pop(2)
mylist
mylist.pop()
mylist
del mylist
mylist
mylist2=['carrot','cabbage','cucumber','brinjal']
del mylist2[2]
mylist2
mylist2.clear()
mylist2
mylist=['mango','apple','cherry','orange',]
mylist.sort()
mylist
thislist=[1,2,3,4,5,6,7,]
thislist.sort()
thislist
mylist.sort(reverse=True)
mylist
thislist.sort(reverse=True)
thislist
thislist.reverse()
thislist
fruits=mylist.copy()
fruits
fruits2=list(mylist)
fruits2
list1=['a','b','c']
list2=[1,2,3,]
list3=list1+list2
list3
list1.extend(list2)
list1
list1.index('a')
list1.index(1)
list2*8
thislist=['anu','sanu','manu']
thislist2=thislist.copy()
thislist2
thislist.index('anu')
thislist2.index('manu')
thislist.append('rinu')
thislist
len(thislist)
thislist

#to print all numbers in list
list1=[1,2,3,4,5,6,7,8,9]
sum=0
for variable in list1:
    sum=sum+variable
print(sum)
