#TUPLE

#TUPLE
mytuple=('mango','apple','cherry')
mytuple
type(mytuple)
len(mytuple)
thistuple=tuple(('kiwi','pineapple','mango','carrot','cabbage','cucumber'))
thistuple
thistuple[-1]
thistuple[]

mytuple=('mango','apple','cherry')
mytuple
type(mytuple)
len(mytuple)
thistuple=tuple(('kiwi','pineapple','mango','carrot','cabbage','cucumber'))
thistuple
thistuple[-1]
thistuple[-4:-1]
thistuple[1:3]
thistuple
thistuple[2:4]
thistuple[::2]
thistuple[::3]
thistuple[-4:-1]
thistuple[::-2]
thistuple[2:3]

tuple1=("a","b","c")
tuple2=(1,2,3)
tuple3=tuple1+tuple2
tuple3
x=tuple3*2
tuple3.count("a")
tuple3.index(1)


x#confused
x.count("a")

tuple[::-1]
x=('kiwi','pineapple','mango','carrot','cabbage','cucumber')
y=list(x)
y
y[4]='apple'
y
x=tuple(y)
x
fruits=('kiwi','pineapple','mango','carrot')
(green,blue,red,yellow)=fruits
green
blue
fruits2=('kiwi','pineapple','mango','carrot','cabbage','cucumber')
(green,blue,*red)=fruits2
green



#TUPLE
mytuple=('mango','apple','cherry')
mytuple
type(mytuple)
len(mytuple)
thistuple=tuple(('kiwi','pineapple','mango','carrot','cabbage','cucumber'))
thistuple
thistuple[-1]
thistuple[-4:-1]
thistuple[1:3]
thistuple
thistuple[2:4]
thistuple[::2]
thistuple[::3]
thistuple[-4:-1]
thistuple[::-2]
thistuple[2:3]
thistuple[::-1]
x=('kiwi','pineapple','mango','carrot','cabbage','cucumber')
y=list(x)
y
y[4]='apple'
y
x=tuple(y)
x
fruits=('kiwi','pineapple','mango','carrot')
(green,blue,red,yellow)=fruits
green
blue
fruits2=('kiwi','pineapple','mango','carrot','cabbage','cucumber')
(green,blue,*red)=fruits2
green
blue
red
tuple1=("a","b","c")
tuple2=(1,2,3)
tuple3=tuple1+tuple2
tuple3
x=tuple3*2
tuple3.count("a")
tuple3.index(1)
x
x.count("a")